title : Perpetual Staircase
tagline: Keep going up!
author :
  name : Ho Ming Li
  email : homingli@gmail.com
  github : homingli
  twitter : horeal
  feedburner : 

navigation :
  - archive.html
  - tags.html
  - categories.html
  - about.md
  
